### ISSUE TITLE
Visitor sign in

### ISSUE THREAD

**Issue by TheMindset** [ocardinaux/thp_next_kitten_project#17]
**Score**

**WHY**

A visitor can became sign up/in

**TODO**

* [ ] `users` controller and views (devise)
* [ ] notification of sign up (devise)
* [ ] redirection to the landing_page 
* [ ] RSpec test

**MUST HAVE**

* [ ] creation of new user in db
