### ISSUE TITLE
User new

### ISSUE THREAD

**Issue by ocardinaux** [ocardinaux/thp_next_kitten_project#2]
**Score**

**WHY**

A User can be create with seed

**TODO**

* [ ] `users` and `profile` db and `User`model with validations
* [ ] seed some `users`
* [ ] RSpec test

**MUST HAVE**

* [ ] creation of new user in db

**Comment by ocardinaux** [comment]
Do we plan to use email confirmations for users?

**Comment by TheMindset** [comment]
Issue too long, I am going to separate the back and the front
