### ISSUE TITLE
Create cart model

### ISSUE THREAD

**Issue by ocardinaux** [ocardinaux/thp_next_kitten_project#20]
**WHY**

User must have a cart

**TODO**

* [x] cart table (has_many cats)
* [x] cart items (cats) table

**MUST HAVE**

* [x] Cart model w/ migration
* [x] CartCat model w/ migration
