### ISSUE TITLE
Feat: add cat to cart

### ISSUE THREAD

**Issue by ocardinaux** [ocardinaux/thp_next_kitten_project#26]
**WHY**

User can add cat to his cart

**TODO**

* [x] restrict to authentified user
* [ ] select current_user/current_cart (find or new)
* [ ] 

**MUST HAVE**

* [ ] a new cat is added to the cart
* [ ] a message indicates the operation went well
