### ISSUE TITLE
Items index front

### ISSUE THREAD

**Issue by ocardinaux** [ocardinaux/thp_next_kitten_project#4]
**WHY**

The visitors/users should see a page with all items

**TODO**

* [ ] items index bootstrap grid view
* [ ] item bootstap card partial
* [ ] adjust route

**MUST HAVE**

* [ ] items index page view, routed to root
