### ISSUE TITLE
Dashboard Admin

### ISSUE THREAD

**Issue by NIcoZF** [ocardinaux/thp_next_kitten_project#44]
**Why**
Dashboard where i can manage item

**ToDo**
* [ ] create views related to cats_controller in admin namespace
* [ ] create button "admin" in root page only visible if current user is admin
* [x] create button to create a new item
* [x] create button to edit item
* [ ] create button to make an item unavailable to be sold

**Must Have**
functional dashboard
