### ISSUE TITLE
Cats Index UX improvements

### ISSUE THREAD

**Issue by NIcoZF** [ocardinaux/thp_next_kitten_project#59]
**WHY**

Make the navigation easier

**TODO**

* [ ] make the cats pictures clickable 
* [ ] add cart icon in the nav bar
* [ ] add animation when signed_in user add picture to cart
* [ ] redirect user to sign_up page by default

**MUST HAVE**

* [ ] cart icon and clickable pictures
