### ISSUE TITLE
Cat index and show page

### ISSUE THREAD

**Issue by ocardinaux** [ocardinaux/thp_next_kitten_project#6]
**WHY**

Visitors/users can see all information about the item

**TODO**

* [ ] add the right code in the controller
* [ ] construct the views page(cat.html.erb)

**MUST HAVE**

* [ ] Item view with all pertinent data from db
