### ISSUE TITLE
Improve Footer

### ISSUE THREAD

**Issue by TheMindset** [ocardinaux/thp_next_kitten_project#66]
**WHY**

Improve UX Design 

**TODO**

* [x] Remove the useless links 
* [x] add links For Our Team
* [x] add icons for Facebook, Twitter etc.

**MUST HAVE**

* [x] A clean footer with Facebook and others icons
