### ISSUE TITLE
Teams View

### ISSUE THREAD

**Issue by TheMindset** [ocardinaux/thp_next_kitten_project#67]
**WHY**

More information about the team how build this app

**TODO**

* [ ] construct the View (About Us)
* [ ] add Links on the Navbar and Footer

**MUST HAVE**

* [ ] The views "About us and the Links that go with
