### ISSUE TITLE
Active Storage - add image to items

### ISSUE THREAD

**Issue by ocardinaux** [ocardinaux/thp_next_kitten_project#7]
**WHY**

Because that's what we sell!

**TODO**

* [ ] set up active storage (dev: local; prod: AWS)
* [ ] include Amazon AWS keys in .env and heroku
* [ ] replace placeholder with actual image in index and show views
* [ ] create namespace admin
* [ ] create a cat controller within the namespace admin - to manage cat images
* [ ] create admin controller to restrict access to namespace admin

**Comment by ocardinaux** [comment]
**LATER**

* [ ] add image upload in admin section
