### ISSUE TITLE
Better navbar cart popup

### ISSUE THREAD

**Issue by ocardinaux** [ocardinaux/thp_next_kitten_project#72]
**TODO/MUST HAVE**

* [ ] add ajax to update badge counter
* [ ] correct count of items (now without quantity)
* [ ] fix position of popup
* [ ] better UI for popup

* [ ] add individual counter badges to cards in index
