### ISSUE TITLE
Cat_controllers with seller methods

### ISSUE THREAD

**Issue by TheMindset** [ocardinaux/thp_next_kitten_project#77]
**WHY**

Sell an Image

**TODO**

* [x] attach a boolean user_id  on cat table
* [x] define the new method in the cat_controller
* [x] add the animation when the sellers put on sale image
* [x] define the edit method in the cat_controller
* [ ] define the update method in the cat_controller
* [ ] add the animation when the seller update the Image
* [ ] add some test for the controllers

**MUST HAVE**

* [ ] the cat_controllers with method and test
