### ISSUE TITLE
Front Sell Bouton

### ISSUE THREAD

**Issue by TheMindset** [ocardinaux/thp_next_kitten_project#79]
**WHY**

Click on "Sell" Bouton

**TODO**

* [x] add the "Sell" Bouton on the navbar
* [x] add the page wich go with

**MUST HAVE**

* [x] the bouton "Sell" and the view cat (new.html.erb)
