### ISSUE TITLE
Application layout files

### ISSUE THREAD

**Issue by ocardinaux** [ocardinaux/thp_next_kitten_project#9]
**WHY**

Global setup for views

**TODO**

* [ ] use boostrap theme
* [ ] setup layout/application
* [ ] create _navbar and _footer partials

**MUST HAVE**

* [ ] General layout of application
