### ISSUE TITLE
Clean database

### ISSUE THREAD

**Issue by TheMindset** [ocardinaux/thp_next_kitten_project#95]
**WHY**

Sell an Image

**TODO**

* [x] remove age column in Cat table
* [x] Add first and last name in Profile Table
* [x] Change Seed (User loop for fill the Profile's Information

**MUST HAVE**

* [x] A clean Database
