### ISSUE TITLE
Update Index view (related : #6 and #4)

### ISSUE THREAD

**Issue by TheMindset** [ocardinaux/thp_next_kitten_project#96]
**WHY**

Sell an Image

**TODO**

* [x] Add "Sell" bouton
* [x] Add "Edit" and "Delete" bouton
* [x] back work for make the edit and Delete bouton if the User = the Seller

**MUST HAVE**

* [x] the three bouton visible and operational
