### ISSUE TITLE
Profile Edit Form

### ISSUE THREAD

**Issue by NIcoZF** [ocardinaux/thp_next_kitten_project#99]
**WHY**

Users must be able to udate their profile informations

**TODO**

* [x] controller method update with permit
* [x] view : Update_form with form_tag needed
* [x] flash message to confirm the update

**MUST HAVE**

functionnal update form
